<a href="https://colab.research.google.com/github/PKatke/PKatke/blob/main/DataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #Scentific Calculations
import pandas as pd #Handle Complex Data Processing

In [2]:
dataset = pd.read_csv('/content/Dummy1.csv')

In [3]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1   Spain   27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3   Spain   38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6   Spain    NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [6]:
x = dataset[['Country','Age','Salary']].values

In [7]:
x

array([['France', 44.0, 72000.0],
       ['Spain ', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain ', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain ', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [10]:
y = dataset[['Purchased']].values

In [11]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [12]:
from sklearn.impute import SimpleImputer

In [13]:
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')

In [14]:
imputer = imputer.fit(x[:,1:3])

In [16]:
x[:,1:3] = imputer.transform(x[:,1:3])

In [17]:
x

array([['France', 44.0, 72000.0],
       ['Spain ', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain ', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain ', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
label_encoder_x=LabelEncoder()

In [24]:
x[:,0] = label_encoder_x.fit_transform(x[:,0])

In [25]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [26]:
 from sklearn.preprocessing import OneHotEncoder

In [27]:
onehotencoder = OneHotEncoder()

In [51]:
 x= onehotencoder.fit_transform(dataset.Country.values.reshape(-1,1)).toarray()

In [52]:
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [30]:
labelencoder_y=LabelEncoder()

In [53]:
y=labelencoder_y.fit_transform(y)

In [32]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [33]:
from sklearn.model_selection import train_test_split

In [36]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [37]:
x_train

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [38]:
x_test

array([[0., 1., 0.],
       [0., 1., 0.]])

In [39]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [40]:
y_test

array([0, 0])

In [42]:
from sklearn.preprocessing import StandardScaler

In [43]:
sc_x=StandardScaler()

In [45]:
x_train=sc_x.fit_transform(x_train)

In [46]:
x_test=sc_x.transform(x_test)

In [47]:
x_train

array([[-1.        ,  2.64575131, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667]])

In [48]:
x_test

array([[-1.        ,  2.64575131, -0.77459667],
       [-1.        ,  2.64575131, -0.77459667]])